version: "3"
services:
  app:
    build: .
    environment:
      - GO_APP_MODE=production
      - DB_CONNECT_STRING=go_app:secret@tcp(database)/truthordare_app?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - database
    links:
      - database
    ports:
      - "1323:1323"
    networks:
      - truthordare_network
  database:
    container_name: database
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=truthordare_app
      - MYSQL_USER=go_app
      - MYSQL_PASSWORD=secret
    ports:
      - "23306:3306"
    networks:
      - truthordare_network

networks:
  truthordare_network:
    driver: bridge