version: "3"
services:
  app:
    build: .
    pull_policy: build
    environment:
      - GO_APP_MODE=production
      - DB_CONNECT_STRING=go_app:secret@tcp(database)/truthordare_app?parseTime=true  # Use the IP address of the database container
    depends_on:
      - database
    networks:
      truthordare_network:
        ipv4_address: 192.168.2.11
  database:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=truthordare_app
      - MYSQL_USER=go_app
      - MYSQL_PASSWORD=secret
    volumes:
      - /data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - truthordare_network


networks:
  truthordare_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/24"