version: "3"
services:
  truth_or_dare:
    build: .
    image: truthordare:latest
    environment:
      - GO_APP_MODE=production
      - DB_CONNECT_STRING=go_app:secret@tcp(truthordare_db)/truthordare_app?parseTime=true  # Use the IP address of the database container
    depends_on:
      - database
  database:
    image: mariadb:latest
    container_name: truthordare_db
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=truthordare_app
      - MARIADB_USER=go_app
      - MARIADB_PASSWORD=secret
    ports:
        - "3306:3306"